# Generated by Django 4.0 on 2022-03-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinBoard', '0002_task_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familyuser',
            unique_together={('user', 'family')},
        ),
    ]
