# Generated by Django 4.0 on 2022-03-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinBoard', '0003_alter_familyuser_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiweTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_tasks', to='pinBoard.user')),
            ],
        ),
    ]
