# Generated by Django 4.0 on 2022-03-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinBoard', '0004_archiwetasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user_invitations', to='pinBoard.user', verbose_name='Imie osoby którą chcesz zaprosić'),
        ),
    ]
