# Generated by Django 4.0 on 2022-03-26 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pinBoard', '0005_alter_invitation_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
